name: mofa
channels:
  - defaults
  - conda-forge
dependencies:
  # Services used by the workflow
  - redis==5.*
  - mongodb
  - parallel  # Used as a launcher

  # Science apps from Conda-Forge
  - chargemol
  - raspa2
