# Install CUDA from Anaconda
name: mofa
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python==3.10.*
  - openssl>3

  # Standard data analysis tools
  - pandas==1.*
  - scipy==1.10.*
  - scikit-learn
  - jupyterlab
  - matplotlib
  - pytest

  # Tools used as part of the ML packages
  - imageio
  - pytorch-lightning
  - wandb

  # Tools to work with crystalline and molecular data
  - openbabel==3.1.*
  - pymatgen==2023.8.10
  - scikit-learn==1.3.0
  - conda-forge::chargemol
  - conda-forge::raspa2

  # Use Conda PyTorch to avoid OpenMP disagreement with other libraries
  - pytorch::pytorch==2.3.*
  - pytorch::pytorch-cuda=11.8
  - cuda-version==11.8

  # Services used by the workflow
  - redis-server
  - mongodb
  - mongo-tools

  - pip
  - pip:
    - git+https://gitlab.com/ase/ase.git
    - git+https://github.com/exalearn/colmena.git  # Fixes for streaming not yet on PyPI
    - rdkit==2023.03.2
    - mace-torch
    - -e ..[test]

